### ISSUE TITLE
state length exceeds 255 characters

### ISSUE THREAD

**Issue by phixion** [custom-components/places#16]
Often times the max length of 255 characters is exceeded for me

```
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.martin. State max length is 255 characters.
2020-01-30 12:55:28 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 405, in _async_write_ha_state
    self.entity_id, state, attr, self.force_update, self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 977, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 721, in __init__
    f"Invalid state encountered for entity id: {entity_id}. "
```

I have set the following options:
zone,place,street_number,street,city,state,postal_code, county, country

I have removed a couple to get rid of the issue is there a better way tofix this?

**Comment by iantrich** [comment]
That's a hard limit in HA, no way around it
