### ISSUE TITLE
No sensor after updating to beta - Home Assistant 2023.6.0b0

### ISSUE THREAD

**Issue by bschatzow** [custom-components/places#180]
This entity is no longer being provided by the places integration. If the entity is no longer in use, delete it in settings.

**Comment by Snuffy2** [comment]
I'm not running the beta and with it being 6/1, I suspect 2023.6 will be out any day now. Are you able to provide any more info and/or [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) so I may be better able to determine what is happening?

**Comment by bschatzow** [comment]
I had the debug logging already setup. 
Not sure if this is helpful. It is the only error in the log with places.

```
Logger: homeassistant.components.sensor
Source: custom_components/places/sensor.py:523
Integration: Sensor (documentation, issues)
First occurred: June 1, 2023 at 9:16:29 PM (1 occurrences)
Last logged: June 1, 2023 at 9:16:29 PM

Error while setting up places platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/places/sensor.py", line 368, in async_setup_entry
    [Places(hass, config, config_entry, name, unique_id)], update_before_add=True
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/places/sensor.py", line 510, in __init__
    self.disable_recorder()
  File "/config/custom_components/places/sensor.py", line 523, in disable_recorder
    ha_history_recorder.entity_filter._exclude_e.add(self.entity_id)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '_exclude_e'
```

**Comment by bschatzow** [comment]
Nothing listed on recorder in the docs.

```
https://rc.home-assistant.io/blog/2023/05/31/release-20236/#connect-and-use-your-existing-network-storage
```

**Comment by Snuffy2** [comment]
v.2.4.1 should at least allow `places` to load in 2023.6+
I'll look to get Disable Recorder actually working again in the future.
