### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by kristofferbj** [custom-components/places#199]
I cannot add or update any device. I am on 2023.8.1 

I get this in the log:

2023-08-10 12:00:15.897 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform places is taking over 10 seconds.
2023-08-10 12:00:26.951 ERROR (MainThread) [homeassistant.components.sensor] places: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/places/sensor.py", line 718, in async_update
    await self._hass.async_add_executor_job(self.do_update, "Scan Interval")
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/places/sensor.py", line 2271, in do_update
    self.parse_osm_dict()
  File "/config/custom_components/places/sensor.py", line 1097, in parse_osm_dict
    if "namedetails" in self.get_attr(ATTR_OSM_DICT) and "name" in self.get_attr(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-08-10 12:00:53.967 ERROR (MainThread) [homeassistant.components.sensor] places: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/places/sensor.py", line 718, in async_update
    await self._hass.async_add_executor_job(self.do_update, "Scan Interval")
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/places/sensor.py", line 2271, in do_update
    self.parse_osm_dict()
  File "/config/custom_components/places/sensor.py", line 1097, in parse_osm_dict
    if "namedetails" in self.get_attr(ATTR_OSM_DICT) and "name" in self.get_attr(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-08-10 12:01:15.762 ERROR (MainThread) [homeassistant.components.sensor] places: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/places/sensor.py", line 718, in async_update
    await self._hass.async_add_executor_job(self.do_update, "Scan Interval")
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/places/sensor.py", line 2271, in do_update
    self.parse_osm_dict()
  File "/config/custom_components/places/sensor.py", line 1097, in parse_osm_dict
    if "namedetails" in self.get_attr(ATTR_OSM_DICT) and "name" in self.get_attr(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-08-10 12:01:28.376 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/places/sensor.py", line 709, in tsc_update
    self.do_update("Track State Change")
  File "/config/custom_components/places/sensor.py", line 2271, in do_update
    self.parse_osm_dict()
  File "/config/custom_components/places/sensor.py", line 1097, in parse_osm_dict
    if "namedetails" in self.get_attr(ATTR_OSM_DICT) and "name" in self.get_attr(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-08-10 12:01:31.532 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/places/sensor.py", line 709, in tsc_update
    self.do_update("Track State Change")
  File "/config/custom_components/places/sensor.py", line 2271, in do_update
    self.parse_osm_dict()
  File "/config/custom_components/places/sensor.py", line 1097, in parse_osm_dict
    if "namedetails" in self.get_attr(ATTR_OSM_DICT) and "name" in self.get_attr(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by Snuffy2** [comment]
Should be fixed in v2.4.4 just released.
