### ISSUE TITLE
Error get_extended_attr and "wikidata" 64 occurrences

### ISSUE THREAD

**Issue by vlad36N** [custom-components/places#251]
Hi, 
Places v2.6.0
Core 2023.11.3
Supervisor 2023.11.6
Operating System 11.1

Have error in Log:

Logger: homeassistant
Source: custom_components/places/sensor.py:1807
Integration: Places: Sensor OpenStreetMap (documentation, issues)
First occurred: 04:24:45 (64 occurrences)
Last logged: 05:47:35

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/places/sensor.py", line 2276, in do_update
    self.get_extended_attr()
  File "/config/custom_components/places/sensor.py", line 1807, in get_extended_attr
    and "wikidata"
        ^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by Snuffy2** [comment]
Hmmm... not seeing why this is giving that error and not able to reproduce on my end. Can you [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and either post that here or email it to me at my7idwq0@mail.snuffy2.com if you prefer.
