### ISSUE TITLE
fequent error in the logs

### ISSUE THREAD

**Issue by Pirol62** [custom-components/places#29]
Since 4 weeks I have this error in the logs:
````
Logger: homeassistant
Source: custom_components/places/sensor.py:568
Integration: places (documentation)
First occurred: 9:00:43 (2 occurrences)
Last logged: 9:01:28

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/places/sensor.py", line 434, in tsc_update
    self.do_update("Track State Change")
  File "/config/custom_components/places/sensor.py", line 568, in do_update
    osm_decoded = json.loads(osm_json_input)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
````
Latest version of HA as well as component.

**Comment by Pirol62** [comment]
The numer of errors is rapidly increasing.
````
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/places/sensor.py:568
Integration: places (documentation)
First occurred: 8:55:14 (20 occurrences)
Last logged: 9:31:08

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/places/sensor.py", line 434, in tsc_update
    self.do_update("Track State Change")
  File "/config/custom_components/places/sensor.py", line 568, in do_update
    osm_decoded = json.loads(osm_json_input)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
````
Does nobody has an idea or can nobody look into the component?

**Comment by Pirol62** [comment]
The error dissapeared meanwhile.
