### ISSUE TITLE
After every HA restart have UnboundLocalError: local variable 'current_location' referenced before assignment

### ISSUE THREAD

**Issue by vlad36N** [custom-components/places#50]
After every HA restart have **UnboundLocalError: local variable 'current_location' referenced before assignment**

Logger: homeassistant.helpers.entity
Source: custom_components/places/sensor.py:518
Integration: places (documentation)
First occurred: 18:17:21 (1 occurrences)
Last logged: 18:17:21

Update for sensor.inna fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/places/sensor.py", line 439, in update
    self.do_update("Scan Interval")
  File "/config/custom_components/places/sensor.py", line 518, in do_update
    if current_location == previous_location:
**UnboundLocalError: local variable 'current_location' referenced before assignment**

Home Assistant 2022.8.5 
Supervisor 2022.08.3 
Operating System 8.4 
Frontend 20220802.0 - latest

**Comment by Snuffy2** [comment]
Should be resolved in v2.0. Please let me know if it is still happening.
