### ISSUE TITLE
New 2.0 version: errors in log

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#54]
After updating to 2.0 the log is flooded by errors:
```
2022-09-20 06:31:21.664 ERROR (MainThread) [homeassistant.components.sensor] places: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
await task
File "/config/custom_components/places/sensor.py", line 485, in async_update
await self._hass.async_add_executor_job(self.do_update, "Scan Interval")
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/places/sensor.py", line 626, in do_update
current_location = new_latitude + "," + new_longitude
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
```
2022-09-20 06:32:52.865 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/places/sensor.py", line 468, in tsc_update
self.do_update("Track State Change")
File "/config/custom_components/places/sensor.py", line 626, in do_update
current_location = new_latitude + "," + new_longitude
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by ildar170975** [comment]
May be this is related:
Entities are not always properly created after HA restart; some of then become "restored".
![image](https://user-images.githubusercontent.com/71872483/191174669-55649fc7-e6bc-47c8-b039-4053de3bf96f.png)
After deletion and HA restart - some another entities are "restored", some just disappear.

**Comment by ildar170975** [comment]
Still errors in the log.
```
2022-09-21 20:20:33.320 ERROR (MainThread) [homeassistant.components.sensor] places: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
await task
File "/config/custom_components/places/sensor.py", line 563, in async_update
await self._hass.async_add_executor_job(self.do_update, "Scan Interval")
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/places/sensor.py", line 686, in do_update
if self.is_float(
File "/config/custom_components/places/sensor.py", line 589, in is_float
float(value)
TypeError: float() argument must be a string or a real number, not 'NoneType'
2022-09-21 20:21:09.181 ERROR (MainThread) [homeassistant.components.sensor] places: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
await task
File "/config/custom_components/places/sensor.py", line 563, in async_update
await self._hass.async_add_executor_job(self.do_update, "Scan Interval")
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/places/sensor.py", line 686, in do_update
if self.is_float(
File "/config/custom_components/places/sensor.py", line 589, in is_float
float(value)
TypeError: float() argument must be a string or a real number, not 'NoneType'
2022-09-21 20:21:31.108 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
self.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self._sslobj.do_handshake()
TimeoutError: [Errno 110] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 389, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=None)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/places/sensor.py", line 546, in tsc_update
self.do_update("Track State Change")
File "/config/custom_components/places/sensor.py", line 968, in do_update
osm_response = get(osm_url)
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
return request("get", url, params=params, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=None)
```

Some sensors are "restored":
![image](https://user-images.githubusercontent.com/71872483/191571017-f45c14fe-eecd-49ca-adb0-766df8e7f6d5.png)

After reloading the integration for some entry:
![image](https://user-images.githubusercontent.com/71872483/191571235-8e1655d9-eb6c-4cc1-b245-78c54b13b888.png)
a corresponding sensor MAY or MAY NOT appear as "normal" (i.e. not "restored").
Anyway, after HA reboot some other sensors may become "restored".


Some sensors are not created at all - yet there are entries for them in this tiny panel:
![image](https://user-images.githubusercontent.com/71872483/191570941-b09c7b01-6653-430f-89d9-5334c2f59dfc.png)

The latest version is installed:
![image](https://user-images.githubusercontent.com/71872483/191570664-cebdfd4b-24d3-4d47-80da-d0c32f3a8944.png)

**I guess this issue must be reopened.**

**Comment by Snuffy2** [comment]
For:
```
File "/config/custom_components/places/sensor.py", line 589, in is_float
float(value)
TypeError: float() argument must be a string or a real number, not 'NoneType'
```
Easy fix. I overlooked this with v2.0.1. Will fix with v.2.0.2
<hr/>

For these 2 errors:
```
raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=None)
```
```
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=None)
```

You had posted very similar errors on this in v1.12 as well:
https://community.home-assistant.io/t/reverse-geocode-sensor-places-using-openstreetmap-custom-component/52230/210

It appears that your connection to the OpenStreetMaps server is timing out. I can catch these errors to handle them more gracefully, but do you know why your connection to the OSM server keeps failing? I've not personally had any issues connecting to the OSM servers reliably.

**Comment by ildar170975** [comment]
> but do you know why your connection to the OSM server keeps failing?

I do not know... Internet works as usual. Also I got this sensor:
```
binary_sensor:
  - platform: ping
    host: google.com
    count: 2
    scan_interval: 60
    name: net_is_available_google

  - platform: ping
    host: ya.ru
    count: 2
    scan_interval: !secret scan_interval__internet_availability
    name: net_is_available_yandex

#######################################################################################################

template:
  - binary_sensor:
      - name: net_is_available_internet
        device_class: connectivity
        state: >-
          {%  set GOOGLE = 'binary_sensor.net_is_available_google' -%}
          {%- set YANDEX = 'binary_sensor.net_is_available_yandex' -%}
          {{ is_state(GOOGLE,'on') or
             is_state(YANDEX,'on') }}
        availability: >-
          {%  set GOOGLE = 'binary_sensor.net_is_available_google' -%}
          {%- set YANDEX = 'binary_sensor.net_is_available_yandex' -%}
          {{ not states(GOOGLE) in ['unavailable','unknown'] or
             not states(YANDEX) in ['unavailable','unknown'] }}
```
i.e. every 1 minute it pings 2 servers (2 attempts) and if both failed than "internet is unavailable".
And usually it only fails at 06:00 when my router reboots.

**Comment by Snuffy2** [comment]
Please try v2.0.2 to see if the is_float errors go away and if it handles Timeouts better for you. I don't really have a way to test the timeout so hopefully this helps.

**Comment by ildar170975** [comment]
Same restored entities after updating "places" & HA reboot:
![image](https://user-images.githubusercontent.com/71872483/191656776-e56b7f35-fa06-4fcc-8056-c012831eb48c.png)

Reloading the integration does not help.

Plenty of these errors:
```
2022-09-22 07:10:01.263 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/places/sensor.py", line 548, in tsc_update
self.do_update("Track State Change")
File "/config/custom_components/places/sensor.py", line 720, in do_update
if new_latitude is not None and new_longitude is not None:
UnboundLocalError: local variable 'new_latitude' referenced before assignment
```

Update seems to be installed:
![image](https://user-images.githubusercontent.com/71872483/191656810-17d63f18-062a-4fa2-a6ca-9e8d903cb07c.png)

**Comment by ildar170975** [comment]
Logs are quickly flooded by errors. Disabled the integration. Impossible to use.

**Comment by Snuffy2** [comment]
v2.0.3 PR #69 should fix the new_latitude/new_longitude errors

I'm unsure on how to fix the timeout issues. v2.0.3 tried to handle the timeouts more gracefully and hopefully it won't throw as many errors if it times out.

I'm unclear if the unavailable entities you are seeing are due to the errors that you have been reporting (and thank you for that BTW) or due to timeout errors. Hopefully once we get these errors all squared away, it will be more clear if those are causing the places entities to become unavailable.

**Comment by ildar170975** [comment]
2.0.4
still plenty of errors:
```
2022-09-27 05:29:14.431 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
self.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self._sslobj.do_handshake()
TimeoutError: [Errno 110] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 389, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=None)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/places/sensor.py", line 1093, in do_update
osm_response = requests.get(osm_url)
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
return request("get", url, params=params, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=None)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/places/sensor.py", line 640, in tsc_update
self.do_update("Track State Change")
File "/config/custom_components/places/sensor.py", line 1097, in do_update
"("
TypeError: can only concatenate str (not "ReadTimeout") to str
```

**Comment by Snuffy2** [comment]
PR #93 
Will add to v2.0.5

**Comment by Pirol62** [comment]
I'm not sure if this error  #94 is related.
Looks quite similar to some errors described above

**Comment by Snuffy2** [comment]
Unrelated, but both are bugs
