### ISSUE TITLE
Error floods my log

### ISSUE THREAD

**Issue by Pirol62** [custom-components/places#94]
This error appears sometimes, when I'm at home, but floods my logfile, when I'm outside
v2.0.4  HA 2022.8.6

Logger: homeassistant
Source: custom_components/places/sensor.py:1342
Integration: Places (documentation, issues)
First occurred: 16:38:06 (148 occurrences)
Last logged: 17:03:30

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/places/sensor.py", line 640, in tsc_update
    self.do_update("Track State Change")
  File "/config/custom_components/places/sensor.py", line 1342, in do_update
    self._place_type.lower() == "house"
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by Snuffy2** [comment]
Thanks to @pippyn (#92), this will be fixed in the next release v2.0.5
